### ISSUE TITLE
Depth Images are All Black

### ISSUE THREAD

**Issue by ChaitanyaGanu** [xiaozhuchacha/Kinect2Toolbox#2]
Hello!
I have been trying to use the depth data from some of the datasets that I created. However, when I open the images from the Windows  Photos app, all I can see is a black rectangle. I tried using OpenCV with Python to read the file and convert it to a numpy array, but after printing the array,I got just zeroes. 

Also the shape of the array is 512X424X3 
How does the depth image have 3 channels?

I am a beginner and do not have much knowledge, can you please help me?

Thanks in advance!

**Comment by xiaozhuchacha** [comment]
Since depth map contains floating number, we can only use 16-bit coding to write the image. Therefore, the default image viewer in Windows cannot preview it. However, if you use MATLAB (sample code included in the project), or OpenCV, you should be able to read the image properly.

The 512*424 is the image size, and you should only have one channel instead of there.

The way I created the variable to store the image is:

IplImage* cvDepthImage = cvCreateImage(cvSize(cDepthWidth, cDepthHeight), IPL_DEPTH_16U, 1);
